### ISSUE TITLE
Fails to build on armv without python2

### ISSUE THREAD

**Issue by bjrne** [websockets/utf-8-validate#106]
When running `npm install utf-8-validate@5.0.9` on an armv6 system (a raspi model B with raspian bullseye and its most recent arvm6 node version 10.15.0 in this case), the build fails since python2 is end-of-life and not installed anymore.

System info:
```bash
$ npm -v
6.7.0
$ node -v
v11.15.0
$ uname -a
Linux piB 5.15.32+ #1538 Thu Mar 31 19:37:58 BST 2022 armv6l GNU/Linux
```

Complete stacktrace:
```bash
$ npm install utf-8-validate@5.0.9

> utf-8-validate@5.0.9 install /home/pi/cyp/node_modules/utf-8-validate
> node-gyp-build

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:299:12)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:999:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:403:11)
gyp ERR! stack     at Socket.emit (events.js:193:13)
gyp ERR! stack     at Pipe._handle.close (net.js:614:12)
gyp ERR! System Linux 5.15.32+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/cyp/node_modules/utf-8-validate
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN cyp@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! utf-8-validate@5.0.9 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the utf-8-validate@5.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by lpinca** [comment]
See https://github.com/websockets/bufferutil/issues/145#issuecomment-1116495550.

**Comment by bjrne** [comment]
Like stated in the other issue, thanks so much for your help! Works now with Node 16.9. 

Zero open issues again, impressive flex  :muscle: :wink:
