### ISSUE TITLE
gyp_main.py: error: no such option: --no-parallel

### ISSUE THREAD

**Issue by borisovg** [websockets/utf-8-validate#17]
```
$ npm install utf-8-validate
-
> utf-8-validate@1.2.1 install /home/borisov/test/npm1/node_modules/utf-8-validate
> node-gyp rebuild

Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.1.0-2-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/borisov/test/npm1/node_modules/utf-8-validate
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the utf-8-validate@1.2.1 install script.
npm ERR! This is most likely a problem with the utf-8-validate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls utf-8-validate
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.1.0-2-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "utf-8-validate"
npm ERR! cwd /home/borisov/test/npm1
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/borisov/test/npm1/npm-debug.log
npm ERR! not ok code 0
```

**Comment by lpinca** [comment]
Closing this as Node.js 0.10 is no longer supported.
