### ISSUE TITLE
Error installing on OS X 10.5

### ISSUE THREAD

**Issue by scott-phillips-sp** [websockets/utf-8-validate#19]
I believe this is an issue with installing the latest version of XCode not creating all the symlinks it use to.  bufferutil had a similar issue, https://github.com/websockets/bufferutil/issues/17.  I was able to fix the issue following the advice in that PR:

$ cd /usr/local/lib
$ sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib
$ sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.4.dylib

Here's the console output of npm install:

```
npm install utf-8-validate

> utf-8-validate@1.1.0 install /Users/scott.phillips/IdeaProjects/cloud-grunt-common/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/validation.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/scott.phillips/.node_modules/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/scott.phillips/.node_modules/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/scott.phillips/IdeaProjects/cloud-grunt-common/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm WARN install:utf-8-validate utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN install:utf-8-validate Exit status 1

> utf-8-validate@1.2.1 install /Users/scott.phillips/IdeaProjects/cloud-grunt-common/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/validation.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/scott.phillips/.node_modules/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/scott.phillips/.node_modules/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/scott.phillips/IdeaProjects/cloud-grunt-common/node_modules/utf-8-validate
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
- nan@1.8.4 node_modules/utf-8-validate/node_modules/nan
npm WARN EPEERINVALID grunt-karma@0.11.2 requires a peer of karma@^0.12 || >= 0.13.0-rc.0 but none was installed.
npm WARN EPEERINVALID karma-junit-reporter@0.3.4 requires a peer of karma@>=0.9 but none was installed.
npm WARN EPEERINVALID karma-phantomjs-launcher@0.2.0 requires a peer of karma@>=0.9 but none was installed.
npm WARN EPACKAGEJSON sailpoint-cloud-grunt-common@0.1.1-snapshot No description
npm WARN EPACKAGEJSON sailpoint-cloud-grunt-common@0.1.1-snapshot license should be a valid SPDX license expression
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/Users/scott.phillips/.node_modules/bin/npm" "install" "utf-8-validate"
npm ERR! node v0.12.0
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE

npm ERR! utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the utf-8-validate@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the utf-8-validate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls utf-8-validate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/scott.phillips/IdeaProjects/cloud-grunt-common/npm-debug.log
```

Cheers!

**Comment by Meekohi** [comment]
I hit this bug as well. `sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib` fixed the issue for me. Thanks!

**Comment by Meekohi** [comment]
Was having this issue also. Fixed with:
`sudo ln -s /usr/lib/libSystem.B.dylib /usr/local/lib/libgcc_s.10.5.dylib`
 as recommended.

**Comment by lpinca** [comment]
Updating the "Command Line Tools" should fix this, closing. Please reopen if needed.
