### ISSUE TITLE
Error installing on node 4.2.1 @ win8/x64

### ISSUE THREAD

**Issue by iki** [websockets/utf-8-validate#24]
There's similar `node-gyp rebuild` error like on linux #18 and mac os #19.
```
VCBUILD : error : project file 'C:\Users\admin\AppData\Roaming\npm\node_modules\gfms\node_modules\utf-8-validate\build\validation.vcproj' was not found or not a valid project file. [C:\Users\admin\AppData\Roaming\npm\node_modules\gfms\node_modules\utf-8-validate\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\node_m
odules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\admin\AppData\Roaming\npm\node_modules\gfms\node_modules\utf-8-validate
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1
```

**Comment by gfody** [comment]
same error here, on server 2012 R2, node 5.10.. I'll report back if I get to the bottom of it

**Comment by gfody** [comment]
I created an environment variable named `VCTargetsPath` with value `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140` and that got it working for me

**Comment by iki** [comment]
@gfody Thank you! Installing VS14 (VS11 didn't work) and setting `vcTargetsPath` worked great!

Added VS14 and `vcTargetsPath` support to my [VC env script](https://gist.github.com/iki/48fe1b0a7d8ff0c4177f).
